LifestraCore.USStateList = [ 
  {title: "", value: "" }, 
  {title: "Alabama", value: "AL" }, 
  {title: "Alaska", value: "AK"}, 
  {title: "Arizona", value: "AZ"},
  {title: "Arkansas", value: "AR"}, 
  {title: "California", value: "CA"}, 
  {title: "Colorado", value: "CO"}, 
  {title: "Connecticut", value: "CT"}, 
  {title: "Delaware", value: "DE"}, 
  {title: "District Of Columbia", value: "DC"}, 
  {title: "Florida", value: "FL"}, 
  {title: "Georgia", value: "GA"}, 
  {title: "Hawaii", value: "HI"}, 
  {title: "Idaho", value: "ID"}, 
  {title: "Illinois", value: "IL"}, 
  {title: "Indiana", value: "IN"}, 
  {title: "Iowa", value: "IA"}, 
  {title: "Kansas", value: "KS"}, 
  {title: "Kentucky", value: "KY"}, 
  {title: "Louisiana", value: "LA"}, 
  {title: "Maine", value: "ME"}, 
  {title: "Maryland", value: "MD"}, 
  {title: "Massachusetts", value: "MA"}, 
  {title: "Michigan", value: "MI"}, 
  {title: "Minnesota", value: "MN"}, 
  {title: "Mississippi", value: "MS"}, 
  {title: "Missouri", value: "MO"}, 
  {title: "Montana", value: "MT"}, 
  {title: "Nebraska", value: "NE"}, 
  {title: "Nevada ", value: "NV"}, 
  {title: "New Hampshire", value: "NH"}, 
  {title: "New Jersey", value: "NJ"}, 
  {title: "New Mexico", value: "NM"}, 
  {title: "New York", value: "NY"}, 
  {title: "North Carolina", value: "NC"}, 
  {title: "North Dakota", value: "ND"}, 
  {title: "Ohio", value: "OH"}, 
  {title: "Oklahoma ", value: "OK"}, 
  {title: "Oregon", value: "OR"}, 
  {title: "Pennsylvania", value: "PA"}, 
  {title: "Rhode Island", value: "RI"}, 
  {title: "South Carolina", value: "SC"}, 
  {title: "South Dakota", value: "SD"}, 
  {title: "Tennessee", value: "TN"}, 
  {title: "Texas", value: "TX"}, 
  {title: "Utah", value: "UT"}, 
  {title: "Vermont", value: "VT"}, 
  {title: "Virginia", value: "VA"}, 
  {title: "Washington", value: "WA"}, 
  {title: "West Virginia", value: "WV"}, 
  {title: "Wisconsin", value: "WI"}, 
  {title: "Wyoming", value: "WY"} 
];

LifestraCore.CountryList = [
  {title: "", value: "" }, 
  {value: "US", title: "United States"},
  {value: "CA", title: "Canada"},
  {value: "AF", title: "Afghanistan"},
  {value: "AL", title: "Albania"},
  {value: "DZ", title: "Algeria"},
  {value: "DS", title: "American Samoa"},
  {value: "AD", title: "Andorra"},
  {value: "AO", title: "Angola"},
  {value: "AI", title: "Anguilla"},
  {value: "AQ", title: "Antarctica"},
  {value: "AG", title: "Antigua and/or Barbuda"},
  {value: "AR", title: "Argentina"},
  {value: "AM", title: "Armenia"},
  {value: "AW", title: "Aruba"},
  {value: "AU", title: "Australia"},
  {value: "AT", title: "Austria"},
  {value: "AZ", title: "Azerbaijan"},
  {value: "BS", title: "Bahamas"},
  {value: "BH", title: "Bahrain"},
  {value: "BD", title: "Bangladesh"},
  {value: "BB", title: "Barbados"},
  {value: "BY", title: "Belarus"},
  {value: "BE", title: "Belgium"},
  {value: "BZ", title: "Belize"},
  {value: "BJ", title: "Benin"},
  {value: "BM", title: "Bermuda"},
  {value: "BT", title: "Bhutan"},
  {value: "BO", title: "Bolivia"},
  {value: "BA", title: "Bosnia and Herzegovina"},
  {value: "BW", title: "Botswana"},
  {value: "BV", title: "Bouvet Island"},
  {value: "BR", title: "Brazil"},
  {value: "IO", title: "British lndian Ocean Territory"},
  {value: "BN", title: "Brunei Darussalam"},
  {value: "BG", title: "Bulgaria"},
  {value: "BF", title: "Burkina Faso"},
  {value: "BI", title: "Burundi"},
  {value: "KH", title: "Cambodia"},
  {value: "CM", title: "Cameroon"},
  {value: "CV", title: "Cape Verde"},
  {value: "KY", title: "Cayman Islands"},
  {value: "CF", title: "Central African Republic"},
  {value: "TD", title: "Chad"},
  {value: "CL", title: "Chile"},
  {value: "CN", title: "China"},
  {value: "CX", title: "Christmas Island"},
  {value: "CC", title: "Cocos (Keeling) Islands"},
  {value: "CO", title: "Colombia"},
  {value: "KM", title: "Comoros"},
  {value: "CG", title: "Congo"},
  {value: "CK", title: "Cook Islands"},
  {value: "CR", title: "Costa Rica"},
  {value: "HR", title: "Croatia (Hrvatska)"},
  {value: "CU", title: "Cuba"},
  {value: "CY", title: "Cyprus"},
  {value: "CZ", title: "Czech Republic"},
  {value: "DK", title: "Denmark"},
  {value: "DJ", title: "Djibouti"},
  {value: "DM", title: "Dominica"},
  {value: "DO", title: "Dominican Republic"},
  {value: "TP", title: "East Timor"},
  {value: "EC", title: "Ecudaor"},
  {value: "EG", title: "Egypt"},
  {value: "SV", title: "El Salvador"},
  {value: "GQ", title: "Equatorial Guinea"},
  {value: "ER", title: "Eritrea"},
  {value: "EE", title: "Estonia"},
  {value: "ET", title: "Ethiopia"},
  {value: "FK", title: "Falkland Islands (Malvinas)"},
  {value: "FO", title: "Faroe Islands"},
  {value: "FJ", title: "Fiji"},
  {value: "FI", title: "Finland"},
  {value: "FR", title: "France"},
  {value: "FX", title: "France, Metropolitan"},
  {value: "GF", title: "French Guiana"},
  {value: "PF", title: "French Polynesia"},
  {value: "TF", title: "French Southern Territories"},
  {value: "GA", title: "Gabon"},
  {value: "GM", title: "Gambia"},
  {value: "GE", title: "Georgia"},
  {value: "DE", title: "Germany"},
  {value: "GH", title: "Ghana"},
  {value: "GI", title: "Gibraltar"},
  {value: "GR", title: "Greece"},
  {value: "GL", title: "Greenland"},
  {value: "GD", title: "Grenada"},
  {value: "GP", title: "Guadeloupe"},
  {value: "GU", title: "Guam"},
  {value: "GT", title: "Guatemala"},
  {value: "GN", title: "Guinea"},
  {value: "GW", title: "Guinea-Bissau"},
  {value: "GY", title: "Guyana"},
  {value: "HT", title: "Haiti"},
  {value: "HM", title: "Heard and Mc Donald Islands"},
  {value: "HN", title: "Honduras"},
  {value: "HK", title: "Hong Kong"},
  {value: "HU", title: "Hungary"},
  {value: "IS", title: "Iceland"},
  {value: "IN", title: "India"},
  {value: "ID", title: "Indonesia"},
  {value: "IR", title: "Iran (Islamic Republic of)"},
  {value: "IQ", title: "Iraq"},
  {value: "IE", title: "Ireland"},
  {value: "IL", title: "Israel"},
  {value: "IT", title: "Italy"},
  {value: "CI", title: "Ivory Coast"},
  {value: "JM", title: "Jamaica"},
  {value: "JP", title: "Japan"},
  {value: "JO", title: "Jordan"},
  {value: "KZ", title: "Kazakhstan"},
  {value: "KE", title: "Kenya"},
  {value: "KI", title: "Kiribati"},
  {value: "KP", title: "Korea, Democratic People's Republic of"},
  {value: "KR", title: "Korea, Republic of"},
  {value: "KW", title: "Kuwait"},
  {value: "KG", title: "Kyrgyzstan"},
  {value: "LA", title: "Lao People's Democratic Republic"},
  {value: "LV", title: "Latvia"},
  {value: "LB", title: "Lebanon"},
  {value: "LS", title: "Lesotho"},
  {value: "LR", title: "Liberia"},
  {value: "LY", title: "Libyan Arab Jamahiriya"},
  {value: "LI", title: "Liechtenstein"},
  {value: "LT", title: "Lithuania"},
  {value: "LU", title: "Luxembourg"},
  {value: "MO", title: "Macau"},
  {value: "MK", title: "Macedonia"},
  {value: "MG", title: "Madagascar"},
  {value: "MW", title: "Malawi"},
  {value: "MY", title: "Malaysia"},
  {value: "MV", title: "Maldives"},
  {value: "ML", title: "Mali"},
  {value: "MT", title: "Malta"},
  {value: "MH", title: "Marshall Islands"},
  {value: "MQ", title: "Martinique"},
  {value: "MR", title: "Mauritania"},
  {value: "MU", title: "Mauritius"},
  {value: "TY", title: "Mayotte"},
  {value: "MX", title: "Mexico"},
  {value: "FM", title: "Micronesia, Federated States of"},
  {value: "MD", title: "Moldova, Republic of"},
  {value: "MC", title: "Monaco"},
  {value: "MN", title: "Mongolia"},
  {value: "MS", title: "Montserrat"},
  {value: "MA", title: "Morocco"},
  {value: "MZ", title: "Mozambique"},
  {value: "MM", title: "Myanmar"},
  {value: "NA", title: "Namibia"},
  {value: "NR", title: "Nauru"},
  {value: "NP", title: "Nepal"},
  {value: "NL", title: "Netherlands"},
  {value: "AN", title: "Netherlands Antilles"},
  {value: "NC", title: "New Caledonia"},
  {value: "NZ", title: "New Zealand"},
  {value: "NI", title: "Nicaragua"},
  {value: "NE", title: "Niger"},
  {value: "NG", title: "Nigeria"},
  {value: "NU", title: "Niue"},
  {value: "NF", title: "Norfork Island"},
  {value: "MP", title: "Northern Mariana Islands"},
  {value: "NO", title: "Norway"},
  {value: "OM", title: "Oman"},
  {value: "PK", title: "Pakistan"},
  {value: "PW", title: "Palau"},
  {value: "PA", title: "Panama"},
  {value: "PG", title: "Papua New Guinea"},
  {value: "PY", title: "Paraguay"},
  {value: "PE", title: "Peru"},
  {value: "PH", title: "Philippines"},
  {value: "PN", title: "Pitcairn"},
  {value: "PL", title: "Poland"},
  {value: "PT", title: "Portugal"},
  {value: "PR", title: "Puerto Rico"},
  {value: "QA", title: "Qatar"},
  {value: "RE", title: "Reunion"},
  {value: "RO", title: "Romania"},
  {value: "RU", title: "Russian Federation"},
  {value: "RW", title: "Rwanda"},
  {value: "KN", title: "Saint Kitts and Nevis"},
  {value: "LC", title: "Saint Lucia"},
  {value: "VC", title: "Saint Vincent and the Grenadines"},
  {value: "WS", title: "Samoa"},
  {value: "SM", title: "San Marino"},
  {value: "ST", title: "Sao Tome and Principe"},
  {value: "SA", title: "Saudi Arabia"},
  {value: "SN", title: "Senegal"},
  {value: "SC", title: "Seychelles"},
  {value: "SL", title: "Sierra Leone"},
  {value: "SG", title: "Singapore"},
  {value: "SK", title: "Slovakia"},
  {value: "SI", title: "Slovenia"},
  {value: "SB", title: "Solomon Islands"},
  {value: "SO", title: "Somalia"},
  {value: "ZA", title: "South Africa"},
  {value: "GS", title: "South Georgia South Sandwich Islands"},
  {value: "ES", title: "Spain"},
  {value: "LK", title: "Sri Lanka"},
  {value: "SH", title: "St. Helena"},
  {value: "PM", title: "St. Pierre and Miquelon"},
  {value: "SD", title: "Sudan"},
  {value: "SR", title: "Suriname"},
  {value: "SJ", title: "Svalbarn and Jan Mayen Islands"},
  {value: "SZ", title: "Swaziland"},
  {value: "SE", title: "Sweden"},
  {value: "CH", title: "Switzerland"},
  {value: "SY", title: "Syrian Arab Republic"},
  {value: "TW", title: "Taiwan"},
  {value: "TJ", title: "Tajikistan"},
  {value: "TZ", title: "Tanzania, United Republic of"},
  {value: "TH", title: "Thailand"},
  {value: "TG", title: "Togo"},
  {value: "TK", title: "Tokelau"},
  {value: "TO", title: "Tonga"},
  {value: "TT", title: "Trinidad and Tobago"},
  {value: "TN", title: "Tunisia"},
  {value: "TR", title: "Turkey"},
  {value: "TM", title: "Turkmenistan"},
  {value: "TC", title: "Turks and Caicos Islands"},
  {value: "TV", title: "Tuvalu"},
  {value: "UG", title: "Uganda"},
  {value: "UA", title: "Ukraine"},
  {value: "AE", title: "United Arab Emirates"},
  {value: "GB", title: "United Kingdom"},
  {value: "UM", title: "United States minor outlying islands"},
  {value: "UY", title: "Uruguay"},
  {value: "UZ", title: "Uzbekistan"},
  {value: "VU", title: "Vanuatu"},
  {value: "VA", title: "Vatican City State"},
  {value: "VE", title: "Venezuela"},
  {value: "VN", title: "Vietnam"},
  {value: "VG", title: "Virigan Islands (British)"},
  {value: "VI", title: "Virgin Islands (U.S.)"},
  {value: "WF", title: "Wallis and Futuna Islands"},
  {value: "EH", title: "Western Sahara"},
  {value: "YE", title: "Yemen"},
  {value: "YU", title: "Yugoslavia"},
  {value: "ZR", title: "Zaire"},
  {value: "ZM", title: "Zambia"},
  {value: "ZW", title: "Zimbabwe"}
];